[package]
name = "rust-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.42", default-features = true }
flate2 = "1.1.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
